# Generated by Django 6.0.6 on 2026-06-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief context about the document.', null=True)),
                ('document', models.FileField(help_text='Upload PDF, Word, or Image.', upload_to='announcements_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography or interests.', null=True)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='member_pics/')),
                ('membership_type', models.CharField(choices=[('FULL', 'Full Member (MBChB Student)'), ('HONORARY', 'Honorary Member (Medical Practitioner)'), ('ASSOCIATE', 'Associate Member (Non-medical/Well-wisher)'), ('CORPORATE', 'Corporate Member (Organization/Donor)')], default='FULL', max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to mark as resigned/suspended.')),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PATRON', 'Patron'), ('BOARD_CHAIR', 'Board of Governors - Chairperson'), ('BOARD_TREASURER', 'Board of Governors - Treasurer'), ('BOARD_STUDENT_REP', 'Board of Governors - Student Rep'), ('BOARD_UNI_ADMIN', 'Board of Governors - University Admin'), ('EXEC_CHAIR', 'Executive - Chairperson'), ('EXEC_VICE_CHAIR', 'Executive - Vice Chairperson'), ('EXEC_GEN_SEC', 'Executive - General Secretary'), ('EXEC_TREASURER', 'Executive - Treasurer'), ('EXEC_PUB_SEC', 'Executive - Publicity Secretary'), ('COMM_EDU', 'Standing Committee - Education Chair'), ('COMM_RES', 'Standing Committee - Research Chair'), ('COMM_MEN', 'Standing Committee - Mentorship & Advocacy Chair'), ('CLASS_REP', 'Class Representative')], max_length=50)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Check if they are currently in office.')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_roles', to='core.member')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.FileField(help_text='Upload the main image for the news post.', upload_to='news_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='Who wrote this?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
