# Generated by Django 6.0.6 on 2026-06-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=200)),
                ('flyer', models.FileField(blank=True, help_text='Upload event flyer or poster', null=True, upload_to='event_flyers/')),
                ('is_upcoming', models.BooleanField(default=True, help_text='Uncheck if the event has already passed.')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FoundingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_in_commission', models.CharField(help_text='e.g., Patron, Vision Bearer, Commissioner', max_length=100)),
                ('bio_or_contribution', models.TextField(blank=True, help_text='Their specific role or contribution to founding KUSS.', null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='founders/')),
            ],
            options={
                'verbose_name_plural': 'Founding Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Full Member, Honorary Member', max_length=50)),
                ('entrance_fee', models.DecimalField(decimal_places=2, help_text='Once-off fee in UGX', max_digits=10)),
                ('subscription_fee', models.DecimalField(decimal_places=2, help_text='Per semester fee in UGX', max_digits=10)),
                ('eligibility', models.TextField(help_text='Who qualifies for this membership? (e.g., Registered MBChB students)')),
            ],
            options={
                'verbose_name_plural': 'Membership Tiers & Fees',
                'ordering': ['name'],
            },
        ),
    ]
