# Generated by Django 6.0.6 on 2026-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_foundingmember_membershiptier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kabale University Surgical Society', max_length=100)),
                ('logo', models.FileField(blank=True, help_text='Upload the official KUSS logo', null=True, upload_to='site_logos/')),
                ('motto', models.CharField(default='Supra et Ultra - Above and Beyond', max_length=200)),
                ('contact_email', models.EmailField(default='info@kuss.ac.ug', max_length=254)),
                ('contact_location', models.CharField(default='Kabale, Uganda', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
